E_1_1～E_4_9までコミット
ddt-syamashita/meikaijava_syamashita pull request #2
Opened 2021-02-03 10:26 UTC by ddt-syamashita

進捗率：100％

レビューお願い致します。

2021-02-22 12:01 UTC, ddt-syamashita commented on meikai_java/src/E_1_1/e_1_1.java
> +		// TODO 自動生成されたメソッド・スタブ
// TODO 自動生成されたメソッド・スタブ
上記のコメント文、他の演習箇所も合わせて削除しました。

2021-02-22 12:01 UTC, ddt-syamashita commented on meikai_java/src/E_1_1/e_1_1.java
> + * 作成日：2/1
指摘いただいたあとの演習には、年を入力して記載しました。

2021-02-22 12:02 UTC, ddt-syamashita commented on meikai_java/src/E_2_1/e_2_1.java
> +		//考察結果→型の不一致: double から int には変換できません と表示されエラーとなる。
エラーとなる理由を記載しました。

2021-02-22 12:03 UTC, ddt-syamashita commented on meikai_java/src/E_2_10/e_2_10.java
> +		Scanner sc2 = new Scanner(System.in);
Scanner sc2 = new Scanner(System.in);
上記、重複Scannerクラスのインスタンス化を削除しました。

2021-02-22 12:08 UTC, ddt-syamashita commented on meikai_java/src/E_2_2/e_2_2.java
> +		int x = 33;
指摘箇所の1文字変数を修正しました。

2021-02-22 12:12 UTC, ddt-syamashita commented on meikai_java/src/E_2_3/e_2_3.java
> +		//改行なしで、指定文字列をコンソールに出力
コメント箇所を修正ました。

2021-02-22 12:29 UTC, ddt-syamashita commented on meikai_java/src/E_2_7/e_2_7.java
> +		int z = rand.nextInt(89) +10;
指摘修正いたしました。

2021-02-24 11:17 UTC, ddt-syamashita commented on meikai_java/src/E_2_8/e_2_8.java
> +		int random = rand.nextInt(10) -5;
指摘箇所修正いたしました。再度レビューお願いします。

2021-02-24 11:27 UTC, ddt-syamashita commented on meikai_java/src/E_3_1/e_3_1.java
> +			System.out.println(input);
指摘箇所を修正しました。再度レビューお願いします。

2021-02-24 11:30 UTC, ddt-syamashita commented on meikai_java/src/E_3_11/e_3_11.java
> +		} else if(data >= 11) {
失礼しました。特に理由はありません。
指摘箇所を修正しました。再レビューお願いいたします。

2021-02-24 11:31 UTC, ddt-syamashita commented on meikai_java/src/E_3_12/e_3_12.java
> +		if(min > input2) min = input2;
指摘箇所を修正しました。
再レビューお願いいたします。

2021-03-03 10:21 UTC, ddt-mentor commented on meikai_java/src/E_3_14/e_3_14.java
> +			System.out.println("変数input2は" + input2 + "です。");
柴田

表示される値が、入力を促す際と出力の際で異なります。
そもそも変数input1ではどういう値であるかがわかりません。
この値は何かを示すようにしてください。

2021-03-03 10:22 UTC, ddt-mentor commented on meikai_java/src/E_3_14/e_3_14.java
> +		}
柴田

値が、input1 < input2 の場合、何も出力されません。

2021-03-03 10:24 UTC, ddt-mentor commented on meikai_java/src/E_3_16/e_3_16.java
> +		int input3 = sc.nextInt();
柴田

問題文では「二つの値」となっていますが、コードでは三つの値をソートしています。

2021-03-03 10:30 UTC, ddt-mentor commented on meikai_java/src/E_3_3/e_3_3.java
> +
柴田

問題文そのままである認識なので、修正は不要ですが、
if文がブロック｛｝で囲まれていないことを認識しておいてください。

2021-03-03 10:32 UTC, ddt-mentor commented on meikai_java/src/E_3_4/e_3_4.java
> +			System.out.println("a と b は同じ値です。");
柴田

else ifとしていますが、else を使用していない理由はありますか？

2021-03-03 10:33 UTC, ddt-mentor commented on meikai_java/src/E_3_6/e_3_6.java
> +		// TODO 自動生成されたメソッド・スタブ
柴田

TODOが残っています。

2021-03-03 10:34 UTC, ddt-mentor commented on meikai_java/src/E_3_7/e_3_7.java
> +			//分岐結果を出力
柴田

else ifとしていますが、else を使用していない理由はありますか？
※理由が正当であれば修正は不要です

2021-03-03 10:34 UTC, ddt-mentor commented on meikai_java/src/E_3_8/e_3_8.java
> +			//優の文言を出力
柴田

else ifとしていますが、else を使用していない理由はありますか？
※理由が正当であれば修正は不要です

2021-03-03 10:34 UTC, ddt-mentor commented on meikai_java/src/E_3_8/e_3_8.java
> +	}
柴田

問題文に指示はありませんが、100より大きな値が入力された場合はどうなりますか？

2021-03-03 10:39 UTC, ddt-mentor commented on meikai_java/src/E_4_1/e_4_1.java
> +		} while (true);
柴田

修正は不要ですが、基本、無限ループは使用しないようにしてください。
今回の処理の場合、終了できず、強制終了することしかできなくなります。
なるべく無限ループは使用しない癖をつけておくことをお勧めします。
（999が入力された場合終了とするなどの仕様が必要になります）

2021-03-03 10:39 UTC, ddt-mentor commented on meikai_java/src/E_4_10/e_4_10.java
> +		// TODO 自動生成されたメソッド・スタブ
柴田

メモ
4-9まで完了状態で4-10をコミットしてしまっているので、マージ等の際に注意してください

2021-03-03 10:41 UTC, ddt-mentor commented on meikai_java/src/E_4_2/e_4_2.java
> +		int randomNum = rand.nextInt(89) + 10;
柴田

生成される値が不正ではありませんか？（10～99になっていますか？）

2021-03-03 10:42 UTC, ddt-mentor commented on meikai_java/src/E_4_2/e_4_2.java
> +			if (randomNum < input) {
柴田

値が同じであった場合、この分岐を実行する必要がないはずですが、実行されてしまいます。

2021-03-03 10:43 UTC, ddt-mentor commented on meikai_java/src/E_4_3/e_4_3.java
> +		//2つ目の値が1つ目の値より小さい場合、出力結果を昇順に表示する
柴田

処理とコメントが少し異なっている気がします。

2021-03-03 10:44 UTC, ddt-mentor commented on meikai_java/src/E_4_4/e_4_4.java
> +	}
柴田

while文終了時にxの値が-1になることが確認できていません

2021-03-03 10:48 UTC, ddt-mentor commented on meikai_java/src/E_4_5/e_4_5.java
> +		}
柴田

e4-4と同様です。確認が不足しています。

2021-03-03 10:53 UTC, ddt-mentor commented on meikai_java/src/E_4_8/e_4_8.java
> +	}
柴田

正しい結果が得られていません。ある程度の整数パターンを試してみてください

2021-03-05 22:03 UTC, ddt-syamashita commented on meikai_java/src/E_3_14/e_3_14.java
> +			System.out.println("変数input2は" + input2 + "です。");
指摘箇所を修正しました。
再レビューお願いいたします。

2021-03-05 22:04 UTC, ddt-syamashita commented on meikai_java/src/E_3_14/e_3_14.java
> +		}
指摘箇所を修正しました。
再レビューお願いいたします。

2021-03-05 22:06 UTC, ddt-syamashita commented on meikai_java/src/E_3_16/e_3_16.java
> +		int input3 = sc.nextInt();
失礼しました。問題文の記載ミスとなります。
修正しましたので、再レビューお願いいたします。

2021-03-05 22:07 UTC, ddt-syamashita commented on meikai_java/src/E_3_3/e_3_3.java
> +
承知しました。

2021-03-05 22:12 UTC, ddt-syamashita commented on meikai_java/src/E_3_4/e_3_4.java
> +			System.out.println("a と b は同じ値です。");
特に理由ありません。
elseを使用したif文に修正しました。

2021-03-05 22:13 UTC, ddt-syamashita commented on meikai_java/src/E_3_6/e_3_6.java
> +		// TODO 自動生成されたメソッド・スタブ
削除修正しました。

2021-03-05 22:20 UTC, ddt-syamashita commented on meikai_java/src/E_3_7/e_3_7.java
> +			//分岐結果を出力
特に理由ありません。
elseを使用したif文に修正しました。

2021-03-05 22:26 UTC, ddt-syamashita commented on meikai_java/src/E_3_8/e_3_8.java
> +			//優の文言を出力
特に理由ありません。
elseを使用したif文に修正しました。

2021-03-05 22:27 UTC, ddt-syamashita commented on meikai_java/src/E_3_8/e_3_8.java
> +	}
修正しました。
再レビューお願いいたします。

2021-03-05 22:28 UTC, ddt-syamashita commented on meikai_java/src/E_4_10/e_4_10.java
> +		// TODO 自動生成されたメソッド・スタブ
失礼しました。今後気を付けます。

2021-03-05 22:34 UTC, ddt-syamashita commented on meikai_java/src/E_4_2/e_4_2.java
> +		int randomNum = rand.nextInt(89) + 10;
修正しました。
再レビューお願いいたします。

2021-03-05 22:40 UTC, ddt-syamashita commented on meikai_java/src/E_4_2/e_4_2.java
> +			if (randomNum < input) {
修正しました。
再レビューお願いいたします。

2021-03-05 22:44 UTC, ddt-syamashita commented on meikai_java/src/E_4_3/e_4_3.java
> +		//2つ目の値が1つ目の値より小さい場合、出力結果を昇順に表示する
修正しました。
再レビューお願いいたします。

2021-03-05 22:51 UTC, ddt-syamashita commented on meikai_java/src/E_4_4/e_4_4.java
> +	}
修正しました。
再レビューお願いいたします。

2021-03-05 23:08 UTC, ddt-syamashita commented on meikai_java/src/E_4_5/e_4_5.java
> +		}
修正しました。
再レビューお願いいたします。

2021-03-05 23:18 UTC, ddt-syamashita commented on meikai_java/src/E_4_8/e_4_8.java
> +	}
修正しました。
再レビューお願いいたします。

2021-03-08 12:12 UTC, ddt-mentor commented on meikai_java/src/E_3_14/e_3_14.java
> +			System.out.println("変数input2は" + input2 + "です。");
成田
「a≦bとなるようにソートしました。」こちらの表記も異なっています。
演習をといた後に自分でも一度実施して違和感に気づけるように気をつけましょう。

2021-03-22 12:00 UTC, ddt-mentor requested changes

2021-03-22 12:14 UTC, hosy96 commented on meikai_java/src/E_4_2/e_4_2.java
> +			if (randomNum < input) {
修正しました。
再レビューお願いいたします。

2021-03-22 12:18 UTC, ddt-syamashita commented on meikai_java/src/E_2_8/e_2_8.java
> +		int random = rand.nextInt(11);
コメント修正しました。
再レビューお願いいたします。

2021-03-22 12:19 UTC, ddt-syamashita commented on meikai_java/src/E_4_2/e_4_2.java
> +		;
失礼いたしました。
削除修正しました。

2021-03-24 11:06 UTC, ddt-mentor commented on meikai_java/src/E_4_3/e_4_3.java
> +
20210324_志田
細かいことですが、整数A・Bそれぞれの入力を求める出力文がコロンではなくセミコロンになってます。

2021-03-24 11:09 UTC, ddt-syamashita commented on meikai_java/src/E_4_2/e_4_2.java
> +			if (randomNum < input) {
修正しました。
再レビューお願いいたします。

2021-03-24 11:14 UTC, ddt-syamashita commented on meikai_java/src/E_4_3/e_4_3.java
> +
失礼しました。
指摘箇所をコロンに修正しました。
再度レビューお願いいたします。

2021-04-12 11:38 UTC, ddt-mentor commented
成田
確認しました。

2021-04-12 11:38 UTC, merged