演習4-10～4-15まで（進捗率100％）
ddt-syamashita/meikaijava_syamashita pull request #3
Opened 2021-02-08 10:48 UTC by ddt-syamashita

演習4-10～4-15実施完了しました。
レビューお願い致します。

2021-02-22 10:48 UTC, ddt-mentor requested changes

2021-02-22 10:48 UTC, ddt-mentor commented on meikai_java/src/E_4_10/E_4_10.java
> +			for (int i = 0; i < input; i++)
for文の内部処理はブロックで囲ってください。(石井)

2021-02-22 10:48 UTC, ddt-mentor commented on meikai_java/src/E_4_14/E_4_14.java
> +		int count;
微々たるものですが、この時点で1で初期化していれば代入コストが削減できます。(石井)

2021-02-22 10:48 UTC, ddt-mentor commented on meikai_java/src/E_4_19/E_4_19.java
> +			if (month >= 3 && month <= 5)
if文はブロックで囲ってください。(石井)

2021-02-22 10:48 UTC, ddt-mentor commented on meikai_java/src/E_4_24/E_4_24.java
> +		for (int i = 2; i < inputNumber; i++) {
1を読み込んだ場合に何も表示されません。(石井)

2021-02-22 10:48 UTC, ddt-mentor commented on meikai_java/src/E_4_25/E4_25.java
> +			if (t == 0)
たとえ1文字であってもブロックで囲ってください。(石井)

2021-02-24 12:18 UTC, ddt-syamashita commented on meikai_java/src/E_4_24/E_4_24.java
> +		for (int i = 2; i < inputNumber; i++) {
指摘箇所を修正しました。
再レビューお願いいたします。

2021-02-24 12:19 UTC, ddt-syamashita commented on meikai_java/src/E_4_25/E4_25.java
> +			if (t == 0)
指摘箇所を修正しました。
再レビューお願いいたします。

2021-02-24 12:19 UTC, ddt-syamashita commented on meikai_java/src/E_4_19/E_4_19.java
> +			if (month >= 3 && month <= 5)
指摘箇所を修正しました。
再レビューお願いいたします。

2021-02-24 12:19 UTC, ddt-syamashita commented on meikai_java/src/E_4_14/E_4_14.java
> +		int count;
ご指摘ありがとうございます。
修正いたしました。

2021-02-24 12:19 UTC, ddt-syamashita commented on meikai_java/src/E_4_10/E_4_10.java
> +			for (int i = 0; i < input; i++)
指摘箇所を修正しました。再レビューお願いいたします。

2021-03-08 12:27 UTC, ddt-mentor commented
成田
確認しました。

2021-03-08 12:27 UTC, merged