2021/03/17　E_6_9～E_6_19 進捗率100%
ddt-syamashita/meikaijava_syamashita pull request #5
Opened 2021-03-17 12:05 UTC by ddt-syamashita

第6章の実施完了しました。
レビューお願いいたします。

2021-04-21 12:13 UTC, ddt-mentor requested changes

2021-04-21 12:13 UTC, ddt-mentor commented on meikai_java/src/E_6_15/E_6_15.java
> +				System.out.print("回答を続けますか？ Yes…1 / No…0： ");
細かいですが、ifで分ける必要があるのは"正解"/"不正解"の出力だけですね。(石井)

2021-04-21 12:13 UTC, ddt-mentor commented on meikai_java/src/E_6_18/E_6_18.java
> +		arrayC = new int[standardInput.nextInt()][];
入力値を直で入れると負の値が入った時に困ったことになります。(石井)

2021-04-21 12:13 UTC, ddt-mentor commented on meikai_java/src/E_6_18/E_6_18.java
> +			arrayC[i] = new int[standardInput.nextInt()];
入力値を直で入れると負の値が入った時に困ったことになります。(石井)

2021-04-21 12:13 UTC, ddt-mentor commented on meikai_java/src/E_6_19/E_6_19.java
> +		int[][] classArray = new int[classNumber][];
入力値を直で入れると負の値が入った時に困ったことになります。(石井)

2021-04-21 12:13 UTC, ddt-mentor commented on meikai_java/src/E_6_19/E_6_19.java
> +		double average = (double) total / studentCount;
studentCountが0にならないことをどこかで保証してください。(石井)

2021-04-21 12:13 UTC, ddt-mentor commented on meikai_java/src/E_6_8/E_6_08.java
> +		double[] doubleArray = new double[(int) element];
入力値を直で入れると負の値が入った時に困ったことになります。(石井)

2021-04-21 12:13 UTC, ddt-mentor commented on meikai_java/src/E_6_8/E_6_08.java
> +		System.out.println("平均値：" + (sum / element));
elementが0にならないことをどこかで保証してください。(石井)

2021-04-22 11:48 UTC, ddt-syamashita commented on meikai_java/src/E_6_11/E_6_11.java
> + * 異なる要素の値をもつことのないように演習6-9 のプログラムを改良したプログラムを作成せよ。
修正しました。

2021-04-22 11:48 UTC, ddt-syamashita commented on meikai_java/src/E_6_11/E_6_11.java
> +			intArray[i] = random.nextInt(10) + 1;
修正しました。
再度レビューお願いいたします。

2021-04-22 11:49 UTC, ddt-syamashita commented on meikai_java/src/E_6_12/E_6_12.java
> +			//異なる要素が同値が持つことのないよう、前段繰り返し回数まで繰り返し探索処理を行う
> 配列内の要素が全て同一だとランダムに並び替えた際に並び変わっているかわからないという問題への対策として入れている
指摘ありがとうございます。対策のため入れているため、未修正とします。

2021-04-22 11:50 UTC, ddt-syamashita commented on meikai_java/src/E_6_14/E_6_14.java
> +		Scanner standardInput2 = new Scanner(System.in);
Scannreインスタンスをひとつに修正しました。
再度レビューお願いいたします。

2021-04-22 11:50 UTC, ddt-syamashita commented on meikai_java/src/E_6_14/E_6_14.java
> +				monthRandom = random.nextInt(12);
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:51 UTC, ddt-syamashita commented on meikai_java/src/E_6_14/E_6_14.java
> +				System.out.print("回答を続けますか？ Yes…1 / No…0： ");
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:51 UTC, ddt-syamashita commented on meikai_java/src/E_6_15/E_6_15.java
> +				weekRandom = random.nextInt(7);
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:51 UTC, ddt-syamashita commented on meikai_java/src/E_6_15/E_6_15.java
> +				System.out.print("回答を続けますか？ Yes…1 / No…0： ");
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:51 UTC, ddt-syamashita commented on meikai_java/src/E_6_18/E_6_18.java
> +		arrayC = new int[standardInput.nextInt()][];
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:51 UTC, ddt-syamashita commented on meikai_java/src/E_6_18/E_6_18.java
> +			arrayC[i] = new int[standardInput.nextInt()];
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:51 UTC, ddt-syamashita commented on meikai_java/src/E_6_19/E_6_19.java
> +		int[][] classArray = new int[classNumber][];
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:52 UTC, ddt-syamashita commented on meikai_java/src/E_6_19/E_6_19.java
> +		double average = (double) total / studentCount;
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:52 UTC, ddt-syamashita commented on meikai_java/src/E_6_8/E_6_08.java
> +		double[] doubleArray = new double[(int) element];
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-04-22 11:52 UTC, ddt-syamashita commented on meikai_java/src/E_6_8/E_6_08.java
> +		System.out.println("平均値：" + (sum / element));
指摘箇所を修正しました。
再度レビューお願いいたします。

2021-05-24 10:01 UTC, merged